FROM rustlang/rust:nightly-bookworm

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch --version 8.5.2 --locked

WORKDIR /app

CMD ["cargo", "watch", "-w", "npc-interactions-bridge", "-w", "common", "-x", "run --bin npc-interactions-bridge"]