FROM rustlang/rust:nightly-bookworm

# Install protobuf compiler
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# The actual source will be mounted as volume
CMD ["cargo", "run", "--bin", "characters-grpc"]
