FROM rustlang/rust:nightly-bookworm

# Install protobuf compiler and cargo-watch for auto-reload
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch --version 8.5.2 --locked

WORKDIR /app

# The actual source will be mounted as volume
CMD ["cargo", "run", "--bin", "characters-grpc"]
